#!/usr/bin/env python
""" commandline tool to grab article metadata from a given url """

import urllib2
import logging
from optparse import OptionParser

from metareadability import metastuff

def main():
    parser = OptionParser(usage="%prog: [options]")
    parser.add_option('-v', '--verbose', action='store_true')
    parser.add_option('-d', '--debug', action='store_true')
    parser.add_option('-u', '--url', help="only test urls containing URL")
    (options, args) = parser.parse_args()

    log_level = logging.ERROR
    if options.debug:
        log_level = logging.DEBUG
    elif options.verbose:
        log_level = logging.INFO

    logging.basicConfig(level=log_level, format='%(message)s')

    for url in args:
        html = urllib2.urlopen(url).read()
        headline,byline,pubdate = metastuff.extract(html,url)
        print "%s,%s,%s,%s" % (url,headline,byline,pubdate)

if __name__ == '__main__':
    main()

