#!/usr/bin/env python

# real-world examples of byline html to parse.
# TODO: turn this into a proper testsuite for byline parsing

import lxml.html
from pprint import pprint
import os
import site

here = os.path.dirname(os.path.abspath(__file__))
site.addsitedir(os.path.join(here,"../.."))
from metareadability import byline

examples = [
    """<li class="article-meta-author">by <a class='i-author' href='http://www.walesonline.co.uk/authors/martin-shipton/'>Martin Shipton</a>, Western Mail</li>""",
    """<a href="/standard-home/columnistarchive/Dick Murray, Transport Correspondent-columnist-3966-archive.do">Dick Murray, Transport Correspondent</a></strong>""",
    """
    <h4 class="left padding7north" style="font-size: 12px;">
			By <span class="bold">Robert Gore-Langton</span>
		</h4>
    """,

    """
    <p class="info">
            <author>By Jane Kirby and Hugh Macknight</author><br/>

            <em>Friday, 24 June 2011</em>
        </p>
    """,
    """<li class="byline">
					                        	        	        	            <a class='contributor'  rel='author' href='http://www.guardian.co.uk/profile/jackshenker'>
	            																		Jack Shenker</a> in Cairo
				</li>
    """,
    """<li class="byline">
					                        	        	        	            <a class='contributor'  rel='author' href='http://www.guardian.co.uk/profile/ianblack'>
	            																		Ian Black</a>, <a href="http://www.guardian.co.uk/world/middleeast" title="More from guardian.co.uk on Middle East">Middle East</a> editor
				</li>
    """,
    """<li class="byline">
					                        	        	        	        	            <a class='contributor'  rel='author' href='http://www.guardian.co.uk/profile/carolinedavies'>
	            																		Caroline Davies</a> and <a class='contributor'  rel='author' href='http://www.guardian.co.uk/profile/jamesrobinson'>
	            																		James Robinson</a>

				</li>
    """,
    """<h4 class="left author" style="font-size: 12px;">By <span class="bold">Peter Dyke &amp; Katie Begley</span></h4>""",
    ]



for html in examples:
    doc = lxml.html.fromstring(html)
    parts = byline.tokenise_byline(doc)

    authors, score = byline.parse_byline_parts(parts)

    print "---"
    print "SCORE:",score
    pprint(parts)
    for a in authors:
        pprint( a )

